maistra/envoy

source/extensions/transport_sockets/tls/openssl_impl.cc
source/extensions/transport_sockets/tls/openssl_impl.h
source/extensions/transport_sockets/tls/ssl_socket.cc
test/extensions/transport_sockets/tls/ssl_socket_test.cc

This fixes MAISTRA-1168.
The issue was that the openssl call (SSL_get_peer_cert_chain) that we used to substitute a boringssl one (SSL_get_peer_full_cert_chain) doesn't return a full certificate chain when called on the server: client peer certificate needs to be retrieved separately (see https://www.openssl.org/docs/man1.1.0/man3/SSL_get_peer_cert_chain.html for more details). I added an implementation of SSL_get_peer_full_cert_chain that emulates boringssl behaviour.

Fixes MAISTRA-1168: added implementation of boringssl function SSL_get_peer_full_cert_chain

---

test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc

connection_balancer_ was deallocated before a call to ~ActiveTcpListener, where it's being used.

Fixes MAISTRA-1167: //test/extensions/filters/listener/proxy_protocol:proxy_protocol_test suite is passing now

---

test/integration/protocol_integration_test.cc
test/test_common/utility.h

Fixes MAISTRA-1167: RetryHostPredicateFilter in protocol_integration_test suite passes now

---

test/extensions/tracers/dynamic_ot/config_test.cc

added an explanation why DynamicOpentracingHttpTracer has been disabled

---

source/extensions/common/crypto/utility_impl.cc
source/extensions/filters/http/lua/lua_filter.cc
source/extensions/filters/http/lua/lua_filter.h
test/common/crypto/utility_test.cc
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/lua_integration_test.cc

This is the second part of a fix for https://issues.redhat.com/browse/MAISTRA-1226. The first part of the fix: https://github.com/Maistra/bssl_wrapper/pull/3

Fixes MAISTRA-1226: added support for importPublicKey in lua filter

---

source/common/http/http1/codec_impl.cc
source/common/network/connection_impl.cc
test/common/network/connection_impl_test.cc
test/integration/integration_test.cc

Port of https://github.com/envoyproxy/envoy/pull/9509

Fixes MAISTRA-1299: fix ASSERT failure and infinite loop when attempting to unset readDisable state on a closed connection

---

bazel/repository_locations.bzl

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]

Updated jwt-verify library to the version used upstream

---

source/common/common/BUILD

Because:
- The runtime version could be different than the version used to
build. This is a dinamically linked library.
- It's more secure not to print the version.

MAISTRA-1279: Do not print OpenSSL version

---

source/extensions/transport_sockets/tls/ssl_socket.cc
source/extensions/transport_sockets/tls/ssl_socket.h

backport of https://github.com/Maistra/envoy/pull/27

Fixes MAISTRA-1564: errno is now being logged when SSL_read() fails

---

docs/root/intro/version_history.rst
source/common/runtime/runtime_features.cc
source/extensions/transport_sockets/tls/BUILD
source/extensions/transport_sockets/tls/context_impl.cc
test/exe/version_out_test.sh
test/extensions/transport_sockets/tls/BUILD
test/extensions/transport_sockets/tls/context_impl_test.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]

MAISTRA-1646: improve domain wildcard matching in tls

---

source/extensions/tracers/zipkin/tracer.cc
test/extensions/tracers/zipkin/tracer_test.cc

false (#13193)
Signed-off-by: Gary Brown <gary@brownuk.com>
Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]

Fixes MAISTRA-1840 : tracing: Fix spankind = CLIENT bug when sharedSpanContext is

---

source/extensions/tracers/zipkin/tracer.cc
test/extensions/tracers/zipkin/tracer_test.cc

tracing: Fix spankind = CLIENT bug when sharedSpanContext is
false (#13193)
Signed-off-by: Gary Brown <gary@brownuk.com>
Signed-off-by: Dmitri Dolguikh <ddolguik@redhat.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]

Fixes MAISTRA-1840

---

source/extensions/transport_sockets/tls/context_config_impl.cc
source/extensions/transport_sockets/tls/context_config_impl.h

This PR modifies the defaults used when running within a FIPS environment.

MAISTRA-1921: Support dynamic crypto based on environment

---

source/extensions/transport_sockets/tls/ssl_socket.cc

This cherry-picks the fix for Maistra-1166 to Maistra-2.0. Creating the PR so that our GitHub tests can run. Will test against Maistra-1859 to confirm that this fixes that.

[WIP] MAISTRA-1166: Treat EAGAIN as SSL_ERROR_WANT_READ

---

test/integration/BUILD
test/integration/h2_fuzz.cc

A SegV was occurring in the test shutdown in the RAND_bytes() call
in OpenSSL library.  This was due to the sequencing of calls between
client/server for connection termination.
Commit Message:
Additional Description:
Risk Level: low
Testing: runs no errors.
Docs Changes: none.
Release Notes:
[Optional Runtime guard:]
Optional Fixes #Issue
MAISTRA-2100

MAISTRA-2100 SegV in test shutdown.

---

bazel/foreign_cc/BUILD
bazel/foreign_cc/luajit.patch
bazel/foreign_cc/moonjit.patch
bazel/repository_locations.bzl
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/wrappers_test.cc
test/test_common/utility.cc
test/test_common/utility_test.cc

Cherry-pick of ffa2f17902ee7a378a9ff3166bba375751cf465b
dependencies: bump LuaJIT to 2.1 branch HEAD @ e9af1ab. (#13474)
LuaJIT 2.1.0-beta3 has the following CVEs, which don't appear
super critical for correctly functioning Lua code but prudence dictates
we should bump anyway:
- CVE-2020-15890: LuaJit through 2.1.0-beta3 has an out-of-bounds read
because __gc handler frame traversal is mishandled.
- CVE-2020-24372: LuaJIT through 2.1.0-beta3 has an out-of-bounds read
in lj_err_run in lj_err.c.
There is no release version beyond 2.1.0-beta3, so using HEAD of 2.1
branch.

Fixes MAISTRA-2200: updated lua-jit

---

bazel/foreign_cc/BUILD
bazel/foreign_cc/luajit.patch
bazel/foreign_cc/moonjit.patch
bazel/repository_locations.bzl
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/wrappers_test.cc
test/test_common/BUILD
test/test_common/utility.cc
test/test_common/utility_test.cc

cherry-pick/port of ffa2f17902ee7a378a9ff3166bba375751cf465b
dependencies: bump LuaJIT to 2.1 branch HEAD @ e9af1ab. (#13474)
LuaJIT 2.1.0-beta3 has the following CVEs, which don't appear
super critical for correctly functioning Lua code but prudence dictates
we should bump anyway:
- CVE-2020-15890: LuaJit through 2.1.0-beta3 has an out-of-bounds read
because __gc handler frame traversal is mishandled.
- CVE-2020-24372: LuaJIT through 2.1.0-beta3 has an out-of-bounds read
in lj_err_run in lj_err.c.
There is no release version beyond 2.1.0-beta3, so using HEAD of 2.1
branch.
Risk level: Medium (if using LuaJIT).
Testing: bazel test //test/... Some unit tests required fixups due to
changes in Lua header map table ordering.
Signed-off-by: Harvey Tuch <htuch@google.com>
Co-authored-by: …

Fixes MAISTRA-2199: update lua-jit for maistra 2.0

---

bazel/foreign_cc/BUILD
bazel/foreign_cc/luajit.patch
bazel/repository_locations.bzl
source/extensions/filters/common/lua/lua.h
test/extensions/filters/http/lua/lua_filter_test.cc
test/extensions/filters/http/lua/wrappers_test.cc
test/test_common/BUILD

Port of ffa2f17902ee7a378a9ff3166bba375751cf465b
dependencies: bump LuaJIT to 2.1 branch HEAD @ e9af1ab. (#13474)
LuaJIT 2.1.0-beta3 has the following CVEs, which don't appear
super critical for correctly functioning Lua code but prudence dictates
we should bump anyway:
- CVE-2020-15890: LuaJit through 2.1.0-beta3 has an out-of-bounds read
because __gc handler frame traversal is mishandled.
- CVE-2020-24372: LuaJIT through 2.1.0-beta3 has an out-of-bounds read
in lj_err_run in lj_err.c.
There is no release version beyond 2.1.0-beta3, so using HEAD of 2.1
branch.
Commit Message:
Additional Description:
Risk Level:
Testing: …

Fixes MAISTRA-1775: updated lua-jit

---

test/extensions/transport_sockets/tls/BUILD
test/extensions/transport_sockets/tls/handshaker_test.cc

This re-enables tls-handshaker tests that were disabled due to issues in test setup, releted to TLS handshake.

Fixes MAISTRA-2121: re-enabled handshaker tests

---

source/extensions/transport_sockets/tls/BUILD
source/extensions/transport_sockets/tls/io_handle_bio.cc
source/extensions/transport_sockets/tls/ssl_socket.cc
test/extensions/transport_sockets/tls/BUILD
test/extensions/transport_sockets/tls/io_handle_bio_test.cc
test/extensions/transport_sockets/tls/ssl_socket_test.cc

This enables io_handle_bio. 
This required replacing access to what is private data-structures in OpenSSL to use BIO and BIO_METHOD api.  
@oschaaf

Fixes MAISTRA-2118:  BIO_new_io_handle is functional under OpenSSL now

---

bazel/foreign_cc/luajit-s390x.patch
bazel/foreign_cc/luajit.patch
bazel/repositories.bzl

Commit Message: Add LuaJIT patch for s390x
Additional Description: This is a followup from comments in https://github.com/maistra/proxy/pull/114
Risk Level: Low
Testing: Scratch build downstream
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: Maintains status-quo on s390x wrt luajit plugin.
/cc @dmitri-d

[OSSM-107] Add LuaJIT patch for s390x

---

test/extensions/transport_sockets/tls/ssl_socket_test.cc

Fix a compilation error in tests.
test/extensions/transport_sockets/tls/ssl_socket_test.cc:466:81: error: non-constant-expression cannot be narrowed from type 'long' to 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size_type' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
std::string ocsp_response{reinterpret_cast<const char*>(response_head), response_len};

Fix a compilation error in ssl_socket_test.cc.
